// <auto-generated />
using System;
using ECommerceApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ECommerceApp.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251003152502_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ECommerceApp.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 3, 15, 25, 2, 27, DateTimeKind.Utc).AddTicks(2067),
                            Description = "Comfortable cotton t-shirt perfect for everyday wear",
                            Image = "https://via.placeholder.com/400x400?text=T-Shirt",
                            Name = "Classic Cotton T-Shirt",
                            Price = 19.99m,
                            UpdatedAt = new DateTime(2025, 10, 3, 15, 25, 2, 27, DateTimeKind.Utc).AddTicks(2069)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 3, 15, 25, 2, 27, DateTimeKind.Utc).AddTicks(2074),
                            Description = "Premium quality denim jeans with a perfect fit",
                            Image = "https://via.placeholder.com/400x400?text=Jeans",
                            Name = "Denim Jeans",
                            Price = 79.99m,
                            UpdatedAt = new DateTime(2025, 10, 3, 15, 25, 2, 27, DateTimeKind.Utc).AddTicks(2075)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 3, 15, 25, 2, 27, DateTimeKind.Utc).AddTicks(2076),
                            Description = "Cozy wool sweater for cold weather",
                            Image = "https://via.placeholder.com/400x400?text=Sweater",
                            Name = "Wool Sweater",
                            Price = 89.99m,
                            UpdatedAt = new DateTime(2025, 10, 3, 15, 25, 2, 27, DateTimeKind.Utc).AddTicks(2076)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
